### ISSUE TITLE
Define events JSON format 

### ISSUE THREAD

**Issue by taboca** [TelaSocial/companion#1]
The events data set will be served via HTTP in a format which is JSON, XML, or HTML (which is a last resort option). This may depend on others and it can prevent work. 
- Low priority: We need to check which is the URL with the whole list of events based in out 0.5 milestone, #FISL15; 
- HIgh priority: Which is the format.

**Comment by taboca** [comment]
So far, the following XML is official: 

http://fisl.org.br/14/papers_ng/public/fast_grid?event_id=3

**Comment by fczuardi** [comment]
from the linked XML, some sample records that may help-us with ou app's models:

``` xml
<event id="3" evaluation_by_area="False">
  <name>FISL14</name>
  <evaluation value="swiss_tournament">swiss tournament</evaluation>
  <status value="closed">closed</status>
  <default_venue id="1">
    <name>Centro de Eventos PUCRS</name>
    <latitude>-30.059632129</latitude>
    <longitude>-51.1763226986</longitude>
    <address>Av. Ipiranga, 6681</address>
    <city_name>Porto Alegre-RS</city_name>
  </default_venue>
</event>
```

``` xml
<slot id="762" date="2013-07-04" hour="13" minute="00" room="7" candidate="791" area="170" title="Free Software and Education (WSL session 1)" value="7" colspan="9" color="C9CDFF" abstract="International Free Software Workshop - paper presentations. See http://softwarelivre.org/wsl/." level="" zone="27"/>
```

``` xml
<person id="1998" name="Renato Candido" candidate="48" main="1"/>
```

``` xml
<room id="8">
  <venue>1</venue>
  <capacity>536</capacity>
  <translation>True</translation>
  <name>40T - GNU</name>
  <position>1</position>
</room>
```

``` xml
<area id="38">
  <name>Administra&#231;&#227;o de Sistemas e VoIP</name>
  <descr>Palestras t&amp;amp;amp;amp;#233;cnicas sobre administra&amp;amp;amp;amp;#231;&amp;amp;amp;amp;#227;o de sistemas livres em geral. Servi&amp;amp;amp;amp;#231;os de rede como MTA’s, gerenciamento de usu&amp;amp;amp;amp;#225;rios e grupos, autentica&amp;amp;amp;amp;#231;&amp;amp;amp;amp;#227;o, monitora&amp;amp;amp;amp;#231;&amp;amp;amp;amp;#227;o, servidores web, infra-estrutura, gerenciamento de sistemas operacionais, ger&amp;amp;amp;amp;#234;ncia de pacotes, gerenciamento de servi&amp;amp;amp;amp;#231;os do sistema, Palestras sobre softwares e protocolos de voz sobre IP, etc.</descr>
  <zone>13</zone>
  <public>True</public>
  <quota>0</quota>
  <color>FFC9C9</color>
</area>
```

``` xml
<zone id="26">
  <name>Aaron Swartz</name>
  <event>3</event>
  <public>True</public>
</zone>
```

``` xml
<recording id="78390" slot-id="292" url="http://hemingway.softwarelivre.org/fisl14/high/40a/sala40a-high-201307031014.ogg"/>
```

**Comment by fczuardi** [comment]
FISL 15 HTML schedule:

http://papers.softwarelivre.org/papers_ng/public/new_grid?day=7

**Comment by fczuardi** [comment]
A quick and simplified draft on how the models may look [ember style](http://emberjs.com/guides/models/defining-models/) based on the info we have so far:

``` javascript
Person = model({
    'name': attr('string'),
    'bio': attr('string'),
    'icon': attr('string'),
    'contact': attr('string')
});

Presentation = model({
    'title': attr('string'),
    'abstract': attr('string'),
    'author': belongsTo('person'),
    'contributors': hasMany('person'),
    'description': attr('string')
});

Track = model({
    'title': attr('string'),
    'sessions': hasMany('session'),
});

SubTrack = Track.extend({
    'parent': belongsTo('track')
});

Room = model({
    'name': attr('string'),
    'capacity': attr('number')
});

Session = model({
    'title': attr('string'),
    'presentation': belongsTo('presentation'),
    'presenters': hasMany('person'),
    'start': attr('date'),
    'duration': attr('number'),
    'room': belongsTo('room'),
    'zone': belongsTo('track'),
    'area': belongsTo('subtrack')
});
```

**Comment by fczuardi** [comment]
the html fallback to json (in case needed) currently generates JSON files ~~like this one: https://github.com/TelaSocial/companion-style/blob/master/src/data/schedule.json~~ [outdated, please don't use that]

**Comment by taboca** [comment]
BTW the formal URL from FISL is  is http://papers.softwarelivre.org/papers_ng/public/fast_grid?event_id=4

**Comment by taboca** [comment]
"Mais um detalhe o campo "descr" das entidades "area" deve ser
ignorado, pois no momento está com valores incompletos ou com
problemas de encoding. No fim das contas não estamos mais apresentando
esse texto em lugar nenhum, então acabamos não corrigindo isso." colega do FISL

**Comment by fczuardi** [comment]
At the moment there are 2 different arrangements for the JSON: grouped by rooms and grouped by time. The files and format can be viewed under the /src/data folder, files schedule_grouped_by_room.json and schedule_grouped_by_time.json

To update this static files using the build system:

```
gulp fisl:fetchXML
gulp fisl:buildJSON
```

The code for generating this data structures from the xml are under /src/scripts/lib/fisl/feed-parser.js

Maybe this issue can be closed

**Comment by fczuardi** [comment]
the current json, based on the event xml is pretty solid at the moment, closing as fixed
