### ISSUE TITLE
Event data which is moved to Android calendar

### ISSUE THREAD

**Issue by taboca** [TelaSocial/companion#29]
This is, so far, to Fabricio, to check against his deliverables. But nevertheless it's a major blocker. 

The data, which is moved to the Android Calendar, needs to be formatted with data which is relevant to the user. Since the Android Calendar may not offer the fields we have, we will simply put some fields in the Description field of the event. These are: 
- [x] Talk title
- [x] Candidate name 
- [x] Zone info 
- [x] Room Information
- [x] Talk description

**Comment by fczuardi** [comment]
Room information was supposed to be already there, but I just noticed that the actual room name is missing, I am working on it.

**Comment by fczuardi** [comment]
after 556e4f01061117807bd5743262964975718a506a all items should be fixed, closing…
