### ISSUE TITLE
Links to map

### ISSUE THREAD

**Issue by taboca** [TelaSocial/companion#30]
This is, so far, against Fabricio - it's a blocker, the hyperlinking function. 

From "slots" events we should offer a hyper link to the map. And possibly a means to focus in the room area. 

41T -> linktomap#41T

Which may open an HTML in the app, or separated..

**Comment by fczuardi** [comment]
The link to the map is working as of 48d305773f93a8d692c9e82dd0a285d2a67b9244 and internally the openMapTab call is already aware of which roomID it should focus, so I am closing this one and will track the remaining bit (the actual focus) on issue #31
