### ISSUE TITLE
Favorite/subscription, and actions  

### ISSUE THREAD

**Issue by taboca** [TelaSocial/companion#32]
This is, so far, to check against Fabricio. And we will check the right date. 
## User Experience

 A means for the user to pick talks, which are moved to his/her inventory, which is a view. The inventory will keep the events and user should be able to take actions from it, such as to add to Calendar, or to simply see all the detailed information about such events. 
## Function
- For ever data load operation, we should maintain a running mechanism that checks if an event, which is in the user's inventory, was changed or not. If these events are changed, the system will provide UI so user knows. 
- The inventory should be kept offline, being initial support Android or whichever is simpler to implement  (web APIs for offline storage). 
## Remarks
- Removing from inventory is subject to discussion - possibly to be implemented as "unstar".
- The actual user experience:  alert dialog, notification, calendar add entry, is a secondary discussion.

**Comment by fczuardi** [comment]
The local part of it is implemented. I am removing 0.3.5 milestone from it because the "check against schedule updates" part of it will be handle in a different milestone

**Comment by fczuardi** [comment]
fixed on v0.4.3
