### ISSUE TITLE
Menu not showed up after initial install launch 

### ISSUE THREAD

**Issue by taboca** [TelaSocial/companion#77]
This was noticed on Nexus 7 with "0.4.4" -> 640267978b624ed8d260fd70f304233ae5e31f3b

Perhaps if we land that "inline version" —  I mean, content which is "like page" as opposite to the metaphor of widget/menu, would this get fixed by impact? 

m

**Comment by fczuardi** [comment]
I first though this could be a case of #65 but I was able to reproduce it in the web version + chrome + changing window sizes. Maybe I update this bug later with a proper steps to reproduce, or if you have them please feel free to do so.

The bug to track the "panel version" of the dropdown menu should be filled separatedly, I am doing it now…

**Comment by fczuardi** [comment]
Ok, filed #78

**Comment by fczuardi** [comment]
closing as invalid since after #78 fix and release @v0.5.0-alpha.1 we don't use a dropdown menu anymore
