### ISSUE TITLE
[Test app 2] Client update for event, initial version 

### ISSUE THREAD

**Issue by taboca** [TelaSocial/companion#9]
Initial code or polling XHR or jQuery. Enabling a view.

**Comment by fczuardi** [comment]
it's not yet polling and updating, but the first load as of [tag v0.2.0](https://github.com/TelaSocial/companion/releases/tag/v0.2.0) does fetch from the server (on android, webapp still has CORS restriction) and renders the view client-side, populating an empty dom element.

Marking as closed.
